/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'yearsOfExperience' : IDL.Nat,
          'technologiesUsed' : IDL.Nat,
          'projectsCompleted' : IDL.Nat,
          'clients' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'yearsOfExperience' : IDL.Nat,
            'technologiesUsed' : IDL.Nat,
            'projectsCompleted' : IDL.Nat,
            'clients' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };